service: openai-secrets-demo

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-1
  layers:
    - {Ref: PythonRequirementsLambdaLayer}  # レイヤーを追加   
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
      allowedMethods:
        - POST
      allowedHeaders:
        - Content-Type

    
  environment:
    SECRET_NAME: OPENAI_API_KEY  # Secrets Managerに登録したシークレット名
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:secret:OPENAI_API_KEY-kWDiZ3

functions:
  invokeOpenAI:
    handler: handlers/invoke_openai.lambda_handler
    events:
      - httpApi:
          path: /invoke-openai
          method: post
    timeout: 29
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  # Dockerを利用して依存関係を正確にパッケージング
    layer: true
    slim: true          # 依存関係をスリム化

package:
  exclude:
    - node_modules/**
    - README.md
    - package-lock.json
    - .git/**
    - package.json
    - requirements.txt
    - requirements.zip
    - unzip_requirements.py    